/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ../public/Roseman.glb 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Model(props) {
  const { scene } = useGLTF('/dist/Roseman.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group position={[0, -0.5, 0]} scale={0.061}>
        <primitive object={nodes.spine} />
        <mesh geometry={nodes.torso.geometry} material={materials['Material.001']} position={[-1.687, 3.511, 3.333]}>
          <mesh geometry={nodes._leaf_right.geometry} material={materials['Material.002']} position={[-3.487, 33.726, 4.185]} />
          <mesh geometry={nodes.b_leaf_left.geometry} material={materials['Material.004']} position={[-12.176, 30.803, 4.199]} />
          <mesh geometry={nodes.leaf_stalk_left.geometry} material={materials['Material.005']} position={[-9.649, 31.319, 4.11]} />
          <mesh geometry={nodes.leaf_stalk_right.geometry} material={materials['Material.011']} position={[-5.737, 31.68, 3.941]} />
          <mesh geometry={nodes.rose.geometry} material={materials['Material.012']} position={[-12.277, 38.222, 6.678]} />
          <mesh geometry={nodes.s_leaf_left.geometry} material={materials['Material.013']} position={[-11.35, 30.313, 4.751]} />
          <mesh geometry={nodes.stalk.geometry} material={materials['Material.014']} position={[-7.932, 31.555, 4.3]} />
          <mesh geometry={nodes.top_leaf_left.geometry} material={materials['Material.015']} position={[-12.893, 34.48, 6.001]} />
          <mesh geometry={nodes.top_leaf_left001.geometry} material={materials['Material.014']} position={[-9.854, 35.809, 6.154]} />
        </mesh>
      </group>
      <spotLight intensity={350.471} angle={Math.PI / 8} penumbra={0.15} decay={2} position={[0, 10.717, 0]} rotation={[-Math.PI / 2, 0, 0]} target={nodes.Spot.target}>
        <primitive object={nodes.Spot.target} position={[0, 0, -1]} />
      </spotLight>
      <spotLight intensity={350.471} angle={Math.PI / 8} penumbra={0.15} decay={2} position={[0, -6.148, 0.811]} rotation={[1.574, 0, 0]} target={nodes.Spot001.target}>
        <primitive object={nodes.Spot001.target} position={[0, 0, -1]} />
      </spotLight>
      
    </group>
  )
}

useGLTF.preload('/Roseman.glb')
